name: Verification of DY* Examples

on:
  push:

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: foa3ucuvi85/fstar-ocaml-emacs@sha256:3d29baf7a766709a9fb7aa0f038039cf302467c40cc45d5412191f4fd083ce06
    steps:  
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: /home/build/repo

      - name: Checkout DY* repo
        run: |
          git clone https://github.com/REPROSEC/dolev-yao-star dolev-yao-star
          cd dolev-yao-star
          git checkout ce75306dc86a00970bd5136fda1d2009dba2096b
        working-directory: /home/build

      - name: Copy examples
        run: |
          cp -r /home/build/repo/dy-star/snippet /home/build/dolev-yao-star
          cp -r /home/build/repo/dy-star/nsl /home/build/dolev-yao-star

      - name: Verify code snippet proving that the attacker cannot have performed any operation between sending and receiving a message
        run: |
          export DY_HOME=/home/build/dolev-yao-star
          make
        working-directory: /home/build/dolev-yao-star/snippet

      - name: Verify modified NSL example proving that the initiator can send the nonces na and nb in plaintext to the network
        run: |
          export DY_HOME=/home/build/dolev-yao-star
          make
        working-directory: /home/build/dolev-yao-star/nsl
